platform :ios, '9.0'
use_frameworks!

target 'NurseCall' do

pod 'CocoaAsyncSocket'   # UDP 通讯 框架

pod 'FMDB'               # sqlite数据库框架

pod 'SAMKeychain'       # 钥匙串框架

pod 'SVProgressHUD'    # 指示器

pod "GCDWebServer", "~> 3.0" # 用于PC导入与导出数据库

pod 'TYAlertController'  # 类似 UIAerController 框架
 
end

