-- 创建所有的表格

--  创建 呼叫设备 表格
CREATE TABLE IF NOT EXISTS CALLDEVICES (

    id INTEGER PRIMARY KEY AUTOINCREMENT ,
    deviceType INTEGER NOT NULL  DEFAULT 0,
    subNetID  INTEGER NOT NULL  DEFAULT 0 ,
    deviceID  INTEGER NOT NULL  DEFAULT 0,
    remark   TEXT NOT NULL DEFAULT 'call device'
);

--  创建 响应设备 表格
CREATE TABLE IF NOT EXISTS RESPONSEDEVICES (

    id INTEGER PRIMARY KEY AUTOINCREMENT ,
    deviceType INTEGER NOT NULL  DEFAULT 0,
    subNetID  INTEGER NOT NULL  DEFAULT 0 ,
    deviceID  INTEGER NOT NULL  DEFAULT 0,
    remark   TEXT NOT NULL DEFAULT 'response device'
);

-- 创建 病床 表格 (对应呼叫设备)
CREATE TABLE IF NOT EXISTS SICKBEDS (
    id INTEGER PRIMARY KEY AUTOINCREMENT ,
    sickRoomID  INTEGER NOT NULL  DEFAULT 0 ,
    callDeviceID INTEGER NOT NULL  DEFAULT 0 ,
    remark   TEXT NOT NULL DEFAULT 'sick bed'
);

-- 创建病房表格 (对病床进行分组)
CREATE TABLE IF NOT EXISTS SICKROOMS (
    id INTEGER PRIMARY KEY AUTOINCREMENT ,
    sickRoomType  INTEGER NOT NULL  DEFAULT 0 ,
    remark   TEXT NOT NULL DEFAULT 'sick room'
);

-- 创建 护士站 表格
CREATE TABLE IF NOT EXISTS NURSESTATION (
    id INTEGER PRIMARY KEY AUTOINCREMENT ,
    sickRoomType  INTEGER NOT NULL  DEFAULT 0 ,
    responseDeviceID INTEGER NOT NULL  DEFAULT 0 ,
    remark   TEXT NOT NULL DEFAULT 'nurse station'
);
