-- 创建所有的表格
--  创建 呼叫设备 表格
CREATE TABLE IF NOT EXISTS CALLDEVICES (

    id INTEGER PRIMARY KEY AUTOINCREMENT ,
    deviceType INTEGER   NOT NULL DEFAULT 0 ,
    subNetID  INTEGER NOT NULL  DEFAULT 0  ,
    deviceID  INTEGER NOT NULL  DEFAULT 0,
    remark   TEXT NOT NULL DEFAULT 'call device'
);

